export const ADD_TICKET = "ADD_TICKET";
export const EDIT_TICKET = "EDIT_TICKET";

export const EDIT_USER_ROLE = "EDIT_USER_ROLE";

export const ADD_PROJECT = "ADD_PROJECT";
export const TOGGLE_USER_ON_PROJECT = "TOGGLE_USER_ON_PROJECT";

export const OVERWRITE_TICKETS = 'OVERWRITE_TICKETS'
export const OVERWRITE_PROJECTS = 'OVERWRITE_PROJECTS'
export const OVERWRITE_USERS = 'OVERWRITE_USERS'