export const ADD_TICKET = "ADD_TICKET";
export const EDIT_TICKET = "EDIT_TICKET";
export const ADD_TICKET_COMMENT = "ADD_TICKET_COMMENT"


export const ADD_PROJECT = "ADD_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const ADD_PROJECT_USER = "ADD_PROJECT_USER";
export const REMOVE_PROJECT_USER = "REMOVE_PROJECT_USER";

export const EDIT_USER_ROLE = "EDIT_USER_ROLE";

export const OVERWRITE_TICKETS = "OVERWRITE_TICKETS";
export const OVERWRITE_PROJECTS = "OVERWRITE_PROJECTS";
export const OVERWRITE_USERS = "OVERWRITE_USERS";
